apiVersion: v1
kind: ConfigMap
metadata:
  name: flowforge-config
  namespace: flowforge-system
data:
  NODE_ENV: "development"
  LOG_LEVEL: "debug"
  DB_HOST: "postgres.flowforge-database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "flowforge_dev"
  REDIS_HOST: "redis.flowforge-messaging.svc.cluster.local"
  REDIS_PORT: "6379"
  JWT_EXPIRES_IN: "24h"
  CORS_ORIGIN: "*"
  API_VERSION: "v1"
  MAX_WORKFLOW_EXECUTIONS: "1000"
  WEBHOOK_TIMEOUT: "30000"
  NODE_EXECUTION_TIMEOUT: "300000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: flowforge-database
data:
  POSTGRES_DB: "flowforge_dev"
  POSTGRES_USER: "flowforge"
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: flowforge-messaging
data:
  redis.conf: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync always
    save 900 1
    save 300 10
    save 60 10000
